-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.docents
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    nationality character varying COLLATE pg_catalog."default" NOT NULL,
    document_type character varying COLLATE pg_catalog."default" NOT NULL,
    document_number character varying COLLATE pg_catalog."default" NOT NULL,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    phone character varying COLLATE pg_catalog."default" NOT NULL,
    "schoolGradeId" uuid,
    CONSTRAINT "PK_f8ccb5bfe5cc596f50a0357cadb" PRIMARY KEY (id),
    CONSTRAINT "UQ_30b4e12ac315ec4c6e8982c3b0a" UNIQUE (document_number)
);

CREATE TABLE IF NOT EXISTS public.faculties
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_fd83e4a09c7182ccf7bdb3770b9" PRIMARY KEY (id),
    CONSTRAINT "UQ_39747c4153c669f1db683e8f231" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.methodologies
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_be6131d4407e0b0396801cd04d1" PRIMARY KEY (id),
    CONSTRAINT "UQ_6c780d50afecfde7555c5c53a50" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.modalities
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_4135bf3c2e5bb971c20b08bbef1" PRIMARY KEY (id),
    CONSTRAINT "UQ_e6de06e62c9e55b41a875f9d4fa" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.pensums
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "idPensumExternal" integer,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    "startYear" character varying COLLATE pg_catalog."default" NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    credits integer NOT NULL,
    "idProgram" uuid,
    CONSTRAINT "PK_19f60c60fcbf6f3c682792c1b0e" PRIMARY KEY (id),
    CONSTRAINT "UQ_PENSUM_PROGRAM" UNIQUE ("idProgram", id)
);

CREATE TABLE IF NOT EXISTS public.program_offerings
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "idProgram" uuid,
    "idMethodology" uuid,
    "idPensum" uuid,
    "idSmmlv" uuid,
    cohort integer NOT NULL,
    semester integer NOT NULL,
    CONSTRAINT "PK_03d864c122fe31913c46f13723d" PRIMARY KEY (id),
    CONSTRAINT "UQ_PROGRAM_COHORT_SEMESTER_METHODOLOGY" UNIQUE ("idProgram", cohort, semester, "idMethodology")
);

CREATE TABLE IF NOT EXISTS public.programs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "idProgramExternal" integer,
    unity character varying COLLATE pg_catalog."default" NOT NULL,
    workday character varying COLLATE pg_catalog."default" NOT NULL,
    "codeCDP" character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default" NOT NULL,
    "idFaculty" uuid,
    "idModality" uuid,
    CONSTRAINT "PK_d43c664bcaafc0e8a06dfd34e05" PRIMARY KEY (id),
    CONSTRAINT "UQ_ba50d0f7b68ee5b73f7e7b8fdf9" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.rates
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    factor_smmlv numeric(6, 2) NOT NULL,
    credit_value_smmlv numeric(6, 2) NOT NULL,
    "modalityId" uuid,
    CONSTRAINT "PK_2c804ed4019b80ce48eedba5cec" PRIMARY KEY (id),
    CONSTRAINT "REL_f77effc033a5f5fec4a6c4a273" UNIQUE ("modalityId")
);

CREATE TABLE IF NOT EXISTS public.school_grades
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    level integer NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_b58246a4baec960c455308a9767" PRIMARY KEY (id),
    CONSTRAINT "UQ_2bb840ff089112de4155324cc28" UNIQUE (level),
    CONSTRAINT "UQ_4e2750f16754411a88f1e9246a2" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.smmlvs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    year integer NOT NULL,
    value numeric(12, 2) NOT NULL,
    CONSTRAINT "PK_ff864cad53a6a7c5de613c1e219" PRIMARY KEY (id),
    CONSTRAINT "UQ_add69d80f0d4c19f03d7a2559bf" UNIQUE (year)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    "isActive" boolean NOT NULL DEFAULT true,
    role users_role_enum NOT NULL DEFAULT 'user'::users_role_enum,
    CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY (id),
    CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE (email)
);

ALTER TABLE IF EXISTS public.docents
    ADD CONSTRAINT "FK_89d094a81fe3db8a2e3d8f74504" FOREIGN KEY ("schoolGradeId")
    REFERENCES public.school_grades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pensums
    ADD CONSTRAINT "FK_d78681b1a99b85b12eb32aa4f11" FOREIGN KEY ("idProgram")
    REFERENCES public.programs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.program_offerings
    ADD CONSTRAINT "FK_8e5df0259a278c0ce7f09acb31d" FOREIGN KEY ("idSmmlv")
    REFERENCES public.smmlvs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.program_offerings
    ADD CONSTRAINT "FK_a4c0728cdb6bda609d8723f93c4" FOREIGN KEY ("idProgram")
    REFERENCES public.programs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.program_offerings
    ADD CONSTRAINT "FK_a9d29892e7185d6cee3671ccc00" FOREIGN KEY ("idMethodology")
    REFERENCES public.methodologies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.program_offerings
    ADD CONSTRAINT "FK_f8771ab48d75d261b752ed5648d" FOREIGN KEY ("idPensum", "idProgram")
    REFERENCES public.pensums (id, "idProgram") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.programs
    ADD CONSTRAINT "FK_082d3780d66da383e88cec08509" FOREIGN KEY ("idFaculty")
    REFERENCES public.faculties (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.programs
    ADD CONSTRAINT "FK_e44c065a7fc92fe500e7305808a" FOREIGN KEY ("idModality")
    REFERENCES public.modalities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rates
    ADD CONSTRAINT "FK_f77effc033a5f5fec4a6c4a273f" FOREIGN KEY ("modalityId")
    REFERENCES public.modalities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_f77effc033a5f5fec4a6c4a273"
    ON public.rates("modalityId");

END;